---
title: "r note"
author: "Lei"
date: "2/15/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## load packages

```{r}
#option command i
library(tidyverse)

library(skimr) #install.packages("skimr")

```

## Load the data
```{r}
coronavirus <- read_csv("https://raw.githubusercontent.com/RamiKrispin/coronavirus/master/csv/coronavirus.csv")

#coronavirus
#head(coronavirus,2)

summary(coronavirus)
skim(coronavirus)

```

## Data wrangling
```{r}
filter(coronavirus, cases > 0)
coronavirus_us <- filter(coronavirus, country == "US") 
filter(coronavirus, country == "US" | country == "Canada")

filter(coronavirus, country %in% c("US","Canada","Mexico"), type == "death")
filter(coronavirus, country %in% c("US","Canada","Mexico") & type == "death")
```
```{r}

x <- filter(coronavirus, country == "US", type == "death") 
sum(x$cases)
sum(filter(coronavirus,country == "US", type == "death")$cases)
```
$ Select function
```{r}
select(coronavirus,date,country,type,cases)
select(coronavirus,-lat,-long)
```
```{r}
select(coronavirus, country:cases)
select(coronavirus, date, everything())
select(coronavirus, contains("o"))
select(coronavirus, ends_with("o"))
```

```{r}
coronavirus_us1 <- filter(coronavirus,country == "US")
coronavirus_us2 <- select(coronavirus_us,-lat,-long,-province)

coronavirus_us1 <- coronavirus_us %>% filter(country == "US")
coronavirus_us3 <- coronavirus_us %>% select(lat,-long,-province)

coronavirus %>%
  filter(country == "US") %>%
  select(-lat, -long, -province)
```


